"""Export species + thermo data as a Cantera-compatible YAML file.

The output can be loaded by `cantera.Solution(yaml_string)` for use in:
- ReactionPathDiagram generation
- Reactor network simulations
- Sensitivity analysis

This is a one-way export: we read NASA polynomial data already validated
in our internal database and re-emit it in the Cantera 3.x YAML format.
"""
from __future__ import annotations

from typing import Iterable

from .nasa_poly import NASA7, NASA9
from .database import lookup, SpeciesEntry


def _composition_dict(formula: dict[str, int]) -> dict[str, int]:
    return dict(formula)


def _nasa7_dict(nasa: NASA7) -> dict:
    return {
        "model": "NASA7",
        "temperature-ranges": [nasa.low.Tmin, nasa.low.Tmax, nasa.high.Tmax],
        "data": [list(nasa.low.a), list(nasa.high.a)],
    }


def _nasa9_dict(nasa: NASA9) -> dict:
    ranges = [r.Tmin for r in nasa.ranges] + [nasa.ranges[-1].Tmax]
    data = [list(r.a) + list(r.b) for r in nasa.ranges]
    return {
        "model": "NASA9",
        "temperature-ranges": ranges,
        "data": data,
    }


def _entry_yaml_dict(entry: SpeciesEntry) -> dict:
    thermo: dict
    if isinstance(entry.evaluator, NASA7):
        thermo = _nasa7_dict(entry.evaluator)
    elif isinstance(entry.evaluator, NASA9):
        thermo = _nasa9_dict(entry.evaluator)
    else:
        raise TypeError(f"unknown evaluator: {type(entry.evaluator)}")
    return {
        "name": entry.species.name,
        "composition": _composition_dict(entry.species.formula),
        "thermo": thermo,
    }


def export_cantera_yaml(species_names: Iterable[str],
                         phase_name: str = "gas") -> str:
    """Return a Cantera-compatible YAML string for the requested species.

    Parameters
    ----------
    species_names : iterable of species names that exist in our DB.
    phase_name    : Cantera phase identifier (e.g. "gas").
    """
    species_dicts = []
    elements_set: set[str] = set()
    skipped: list[str] = []
    for name in species_names:
        e = lookup(name)
        if e is None:
            skipped.append(name)
            continue
        species_dicts.append(_entry_yaml_dict(e))
        elements_set.update(e.species.formula.keys())

    elements = sorted(elements_set)
    species_list = [s["name"] for s in species_dicts]
    doc = {
        "description": (
            "Generated by oscillo_plasma_calc.thermo.cantera_export. "
            "Source: NASA Glenn / GRI-Mech / CEA via Cantera-licensed YAML."
        ),
        "phases": [{
            "name": phase_name,
            "thermo": "ideal-gas",
            "elements": elements,
            "species": species_list,
            "kinetics": "gas",
            "transport": "mixture-averaged",
            "state": {"T": 300.0, "P": "1 atm"},
        }],
        "species": species_dicts,
    }
    if skipped:
        doc["skipped_species_not_in_db"] = skipped

    # We avoid importing yaml here to keep this module dependency-light when
    # used as a string builder. The caller can dump via PyYAML, ruamel, or
    # write a quick custom emitter. We provide a default.
    import yaml
    return yaml.safe_dump(doc, sort_keys=False, allow_unicode=True)


def write_cantera_yaml(species_names: Iterable[str], path,
                        phase_name: str = "gas") -> str:
    """Convenience: write the YAML to disk and return the file path."""
    text = export_cantera_yaml(species_names, phase_name=phase_name)
    from pathlib import Path
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8")
    return str(p)
